name: poker-base
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Santiago Weight
github: santiweight/Exploit
license: BSD3
description: Please see the README on GitHub at <https://github.com/githubuser/Exploit#readme>
copyright: 2019 Santiago Weight
maintainer: santiago.weight@gmail.com

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall

tests:
  exploit-poker-test:
    source-dirs:
    - test
    main: Driver.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    dependencies:
    - poker-base

dependencies:
- esqueleto
- serialise
- deepseq
- monad-logger
- persistent
- persistent-template
- persistent-postgresql
- attoparsec
- base-compat
- string-conversions
- lucid
- servant-lucid
- servant-snap
- servant
# - servant-server
- wai
- warp
- http-media
- time
- optparse-applicative
- snap-core
- syb
- containers
- polysemy
- uniplate
- singletons
- deriving-compat
- comonad
- array
- recursion-schemes
- free
- aeson
- async
- base
- bytestring
- containers
- data-default
- time
- directory
- do-notation
- either
- errors
- filepath
- generic-arbitrary
- generic-data
- tasty-discover
- HUnit
- lens
- megaparsec
- monad-loops
- mtl
- polysemy-plugin
- prettyprinter
- QuickCheck
- quickcheck-assertions
- resourcet
- random-shuffle
- scientific
- sort
- tasty
- tasty-hunit
- tasty-hspec
- tasty-quickcheck
- text
- transformers
- uniplate
- unordered-containers
- vector
default-extensions:
- ConstraintKinds
- DataKinds
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- GADTs
- LambdaCase
- LiberalTypeSynonyms
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeOperators
- TypeFamilies
- UnicodeSyntax
- TemplateHaskell